#!/bin/bash
# =============================================================================
# provisioning/proxy.sh - COGSI CA2 / Part 2
# -----------------------------------------------------------------------------
# Turns the proxy machine into the single entry point of the environment:
# Nginx listens on port 80 and forwards every request to the Bookstore on the
# app machine, over the private network.
#
# Environment (set by the Vagrantfile):
#   APP_HOST   hostname of the app machine
#   APP_PORT   HTTP port of the Bookstore
#
# Idempotence: the site file is replaced only when it differs, the result is
# validated with `nginx -t`, and Nginx is reloaded only after a change.
# =============================================================================

set -euo pipefail

export DEBIAN_FRONTEND=noninteractive
export NEEDRESTART_SUSPEND=1

APP_HOST="${APP_HOST:-app}"
APP_PORT="${APP_PORT:-8080}"
SITE="/etc/nginx/sites-available/bookstore"

echo "================================================="
echo "Provisioning the proxy machine..."
echo "================================================="

if dpkg -s nginx >/dev/null 2>&1; then
    echo "[OK] nginx is already installed."
else
    echo "[INSTALL] Installing: nginx"
    apt-get update -qq
    apt-get install -y -qq -o Dpkg::Use-Pty=0 nginx >/dev/null
fi

site=$(mktemp)
cat >"$site" <<EOF
# Managed by provisioning/proxy.sh - manual changes are overwritten.
upstream bookstore {
    server ${APP_HOST}:${APP_PORT};
}

server {
    listen 80 default_server;
    server_name _;

    location / {
        proxy_pass http://bookstore;

        # Pass the address the client used, port included, so that the links
        # generated by the application (HATEOAS) point back to the proxy.
        proxy_set_header Host              \$http_host;
        proxy_set_header X-Real-IP         \$remote_addr;
        proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        proxy_connect_timeout 5s;
        proxy_read_timeout    60s;
    }
}
EOF

changed=false
if cmp -s "$site" "$SITE"; then
    echo "[OK] $SITE is up to date."
else
    install -m 0644 "$site" "$SITE"
    changed=true
    echo "[CONFIG] $SITE"
fi
rm -f "$site"

if [ "$(readlink -f /etc/nginx/sites-enabled/bookstore 2>/dev/null)" != "$SITE" ]; then
    ln -sfn "$SITE" /etc/nginx/sites-enabled/bookstore
    changed=true
    echo "[CONFIG] Site bookstore enabled."
fi

if [ -e /etc/nginx/sites-enabled/default ]; then
    rm -f /etc/nginx/sites-enabled/default
    changed=true
    echo "[CONFIG] Default site disabled."
fi

nginx -t 2>&1 | sed 's/^/[CHECK] /'

systemctl enable --quiet nginx
if ! systemctl is-active --quiet nginx; then
    systemctl start nginx
    echo "[START] nginx"
elif [ "$changed" = true ]; then
    systemctl reload nginx
    echo "[RELOAD] nginx - its configuration changed."
else
    echo "[OK] nginx is already running."
fi

status=$(curl -s -o /dev/null -w '%{http_code}' "http://127.0.0.1/actuator/health" || true)
echo "[INFO] GET http://127.0.0.1/actuator/health through the proxy -> HTTP $status"

echo "================================================="
echo "Proxy machine ready."
echo "================================================="
